# Generated by Django 5.2.1 on 2025-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do cliente.', max_length=255, verbose_name='Nome do Cliente')),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone do cliente (opcional).', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, help_text='Endereço de e-mail do cliente (opcional).', max_length=254, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
