# Generated by Django 5.2.1 on 2025-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_customer',
            field=models.BooleanField(default=False, help_text='Marque esta opção se esta forma de pagamento exige a associação de um cliente à venda (ex: Fiado).', verbose_name='Exige Cliente'),
        ),
    ]
