# Generated by Django 5.2.1 on 2025-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_create_default_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Caixa 01, Terminal de Vendas, Balcão', max_length=100, unique=True, verbose_name='Nome do Ponto de Venda')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar este ponto de venda.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ponto de Venda',
                'verbose_name_plural': 'Pontos de Venda',
                'ordering': ['name'],
            },
        ),
    ]
