# Generated by Django 5.2.1 on 2025-06-30 15:01

from django.db import migrations

def create_default_pos(apps, schema_editor):
    """
    Cria um Ponto de Venda padrão.
    """
    PointOfSale = apps.get_model('caixa', 'PointOfSale')
    PointOfSale.objects.get_or_create(
        id=1, # Garante que o ID seja 1
        defaults={'name': 'Caixa 01', 'is_active': True}
    )

def remove_default_pos(apps, schema_editor):
    """
    Remove o Ponto de Venda padrão.
    """
    PointOfSale = apps.get_model('caixa', 'PointOfSale')
    PointOfSale.objects.filter(id=1, name='Caixa 01').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_pointofsale'),
    ]

    operations = [
        migrations.RunPython(create_default_pos, reverse_code=remove_default_pos),
    ]