# Generated by Django 5.2.1 on 2025-05-20 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor total da venda.', max_digits=10, verbose_name='Valor Total')),
                ('payment_method', models.CharField(help_text='Forma de pagamento utilizada (Ex: Pix, Dinheiro, Cartão de Crédito).', max_length=50, verbose_name='Forma de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Venda')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantidade vendida deste produto.', verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço do produto no momento da venda.', max_digits=10, verbose_name='Preço Unitário na Venda')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal para este item (quantidade * preço unitário).', max_digits=10, verbose_name='Subtotal do Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
