# Generated by Django 5.2.1 on 2025-05-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Valor pago com esta forma de pagamento.', max_digits=10, verbose_name='Valor Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('payment_method_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.paymentmethod', verbose_name='Forma de Pagamento')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento da Venda',
                'verbose_name_plural': 'Pagamentos da Venda',
                'ordering': ['created_at'],
            },
        ),
    ]
