# Generated by Django 5.2.1 on 2025-05-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_payment_method_salepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='Desconhecido', help_text='Forma de pagamento utilizada (Ex: Pix, Dinheiro, Cartão de Crédito).', max_length=50, verbose_name='Forma de Pagamento'),
        ),
        migrations.DeleteModel(
            name='SalePayment',
        ),
    ]
