# Generated by Django 5.2.1 on 2025-06-09 20:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        ('sales', '0003_sale_payment_method_delete_salepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Total da Venda'),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.paymentmethod', verbose_name='Forma de Pagamento')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento da Venda',
                'verbose_name_plural': 'Pagamentos da Venda',
                'ordering': ['created_at'],
            },
        ),
    ]
