# Generated by Django 5.2.1 on 2025-06-30 13:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_payment_method_alter_sale_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do troco devolvido ao cliente.', max_digits=10, verbose_name='Valor do Troco'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade vendida deste produto (pode ser decimal).', max_digits=10, verbose_name='Quantidade'),
        ),
    ]
