# Generated by Django 5.2.1 on 2025-06-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_customer'),
        ('caixa', '0005_create_default_pos'), # Depende da criação do POS padrão
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='point_of_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='caixa.pointofsale', verbose_name='Ponto de Venda'),
            preserve_default=False,
        ),
    ]
