# Generated by Django 5.2.1 on 2025-05-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do produto.', max_length=255, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do produto (opcional).', null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço unitário de venda do produto.', max_digits=10, verbose_name='Preço de Venda')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário de compra do produto (opcional).', max_digits=10, null=True, verbose_name='Preço de Compra')),
                ('internal_code', models.CharField(help_text='Código interno/SKU único para o produto.', max_length=50, unique=True, verbose_name='Código Interno')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Quantidade atual do produto em estoque.', verbose_name='Quantidade em Estoque')),
                ('barcode', models.CharField(blank=True, help_text='Código de barras do produto (opcional, mas recomendado).', max_length=100, null=True, unique=True, verbose_name='Código de Barras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
